#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.12"
# dependencies = [
#     "ozconf",
#     "pyyaml>=6",
#     "pydantic>=2",
# ]
#
# [tool.uv.sources]
# ozconf = { path = "/Users/ky/Documents/code/ozconf", editable = true }
# ///
"""Run the ozconf conformance suite against every registered dingus.

To register a dingus, add to dinguses/ with a name that matches`*_dingus.py`.
The dingus must be runnable with uv run --script (i.e., has the PEP 723 metadata).

To run, use the following command.
    uv run --script scripts/run_conformance_tests.py
"""
import argparse
import json
import os
import re
import subprocess
import sys
import warnings
from collections import Counter
from dataclasses import dataclass
from pathlib import Path
from typing import Literal

import yaml
from models import ConformanceResult

ROOT = Path(__file__).resolve().parent.parent
DINGUS_DIR = ROOT / "dinguses"
LOCAL_RESULTS_DIR = ROOT / "conformance_results" / "local"

# Registration is the filesystem: any file matching this glob is a tool under

DINGUS_GLOB = "*_dingus.py"
DINGUS_SUFFIX = "_dingus"


# The kind of ozconf test to run
KIND = "parse_attributes"
COLUMN_SUFFIX = "attributes"

# Only `core` is scored. This excludes the "strict" tests.
PROFILE = "core"

# Timeout thresholds
RUN_TIMEOUT_SECONDS = 900.0
DESCRIBE_TIMEOUT_SECONDS = 120.0
MAX_REPORTED_ERROR_KINDS = 5

# Environment variables for Rich to make it easier to scrape/parse the ozconf results
TERMINAL_SETUP_ENVAR = {"COLUMNS": "500", "TERM": "dumb", "NO_COLOR": "1"}

# Regex pattern for parsing the ozconf result
# The slug can probably be used later when we break results down by test.
RESULT_PATTERN = re.compile(
    r"^(?P<slug>\S+)\s+(?P<status>pass|fail|error|skip)(?:\s+(?P<message>.*?))?\s*$"
)

# Categories of outcomes for a test
Status = Literal["pass", "fail", "error", "skip"]

# Header for the report yaml file.
DOCUMENT_HEADER = """\
# Generated by scripts/run_conformance_tests.py - do not edit by hand.
#
# Each `values` entry is the pass rate over the ozconf conformance cases for one
# OME-Zarr version. A column with no cases is omitted rather than set to zero.
"""


@dataclass(frozen=True)
class Tool:
    """A registered dingus and the implementation it reports itself to be."""

    path: Path
    id: str
    name: str
    version: str
    homepage: str | None

    @property
    def command(self) -> list[str]:
        """The command ozconf invokes; ozconf appends the case path to it."""
        return ["uv", "run", "--script", str(self.path)]

    @property
    def output_file(self) -> Path:
        return LOCAL_RESULTS_DIR / f"{self.id}.yaml"


@dataclass(frozen=True)
class TestResult:
    """One row of ozconf's results table."""

    slug: str
    column_id: str
    status: Status
    message: str | None


@dataclass(frozen=True)
class TestSummary:
    """Aggregated outcomes for one column of the dashboard table."""

    column_id: str
    passed: int
    failed: int
    errored: int
    skipped: int

    @property
    def total(self) -> int:
        return self.passed + self.failed + self.errored + self.skipped

    @property
    def percentage(self) -> float:
        """The pass rate, 0-100. Anything not a pass counts against it."""
        return round(100.0 * self.passed / self.total, 1)


def run_ozconf(command: list[str]) -> str:
    """Run an ozconf subcommand and return its stdout.

    Parameters
    ----------
    command : list[str]
        The full command line to run.

    Returns
    -------
    str
        The captured stdout.

    Raises
    ------
    ValueError
        If ozconf exits nonzero or doesn't finish within RUN_TIMEOUT_SECONDS.
    """
    try:
        completed = subprocess.run(
            command,
            capture_output=True,
            text=True,
            timeout=RUN_TIMEOUT_SECONDS,
            env={**os.environ, **TERMINAL_SETUP_ENVAR},
        )
    except subprocess.TimeoutExpired:
        raise ValueError(
            f"ozconf did not finish within {RUN_TIMEOUT_SECONDS:g}s."
        )

    if completed.returncode != 0:
        raise ValueError(
            f"ozconf exited {completed.returncode}."
        )

    return completed.stdout


def describe(path: Path) -> Tool:
    """Ask a dingus what implementation it tests.

    Parameters
    ----------
    path : Path
        Path to the dingus script.

    Returns
    -------
    Tool
        The described tool.

    Raises
    ------
    ValueError
        If the dingus fails, times out, prints something other than a JSON
        object with the required fields, or reports an id that doesn't match
        its filename.
    """
    command = ["uv", "run", "--script", str(path), "--describe"]
    try:
        completed = subprocess.run(
            command,
            capture_output=True,
            text=True,
            timeout=DESCRIBE_TIMEOUT_SECONDS,
        )
    except subprocess.TimeoutExpired:
        raise ValueError(
            f"Tool description timed out."
        )

    if completed.returncode != 0:
        raise ValueError(
            f"--describe exited {completed.returncode}."
        )

    try:
        described = json.loads(completed.stdout)
    except json.JSONDecodeError:
        raise ValueError(
            f"--describe did not print JSON: {completed.stdout.strip()!r}"
        )

    missing = [key for key in ("id", "name", "version") if not described.get(key)]
    if missing:
        raise ValueError(f"--describe omitted required field(s) {missing}")

    # The id names the output file, so a mismatch would let a dingus write over
    # a tool it isn't. Requiring it to match the filename keeps the directory
    # listing an honest index of what gets written.
    expected_id = path.stem.removesuffix(DINGUS_SUFFIX)
    if described["id"] != expected_id:
        raise ValueError(
            f"--describe reported id {described['id']!r} but the filename "
            f"implies {expected_id!r}."
        )

    homepage = described.get("homepage")
    return Tool(
        path=path,
        id=str(described["id"]),
        name=str(described["name"]),
        version=str(described["version"]),
        homepage=str(homepage) if homepage else None,
    )


def discover() -> list[Path]:
    """Find the registered dingus scripts in DINGUS_DIR.

    Returns
    -------
    list[Path]
        The dingus scripts, sorted by path.

    Raises
    ------
    SystemExit
        If the directory is missing or holds no dinguses - either way there is
        nothing to test.
    """
    if not DINGUS_DIR.is_dir():
        raise SystemExit(f"error: no dingus directory at {DINGUS_DIR}")

    paths = sorted(DINGUS_DIR.glob(DINGUS_GLOB))
    if not paths:
        raise SystemExit(
            f"error: no {DINGUS_GLOB} files in {DINGUS_DIR}; see its README.md."
        )
    return paths


def column_id_for(slug: str) -> str:
    """Return the columns.yaml column id a result slug contributes to.

    Parameters
    ----------
    slug : str
        An ozconf slug, `kind/version/profile/validity/name`.

    Returns
    -------
    str
        The column id, e.g. "v0.4-attributes".

    Raises
    ------
    ValueError
        If the slug is malformed, or names a kind or profile this run didn't
        ask for - which would mean the filters weren't applied and the scores
        would silently cover the wrong cases.
    """
    # expected format is kind/version/profile/valid_or_invalid/name
    # see the ozconf case directories
    # todo: improve. this is brittle
    parts = slug.split("/", 4)
    if len(parts) != 5:
        raise ValueError(f"cannot parse ozconf slug {slug!r}")

    kind, version, profile, _validity, _name = parts
    if kind != KIND or profile != PROFILE:
        raise ValueError(
            f"ozconf returned a '{kind}/{profile}' case ({slug}) but this run "
            f"asked for '{KIND}/{PROFILE}'; the filters were not applied."
        )
    return f"{version}-{COLUMN_SUFFIX}"


def parse_results(stdout: str) -> list[TestResult]:
    """Parse ozconf's results table.

    Parameters
    ----------
    stdout : str
        The captured stdout of `ozconf test`.

    Returns
    -------
    list[Outcome]
        One outcome per printed row.

    Raises
    ------
    ValueError
        If any non-blank line doesn't match `RESULT_PATTERN`. Skipping such a
        line would drop a case from the denominator and inflate the score, so
        an unrecognized line is fatal - it means ozconf's output format moved,
        or Rich wrapped the table despite `SCRAPE_ENV`.
    """
    outcomes: list[TestResult] = []
    for number, line in enumerate(stdout.splitlines(), start=1):
        if not line.strip():
            continue
        match = RESULT_PATTERN.match(line.rstrip())
        if match is None:
            raise ValueError(
                f"could not parse line {number} of ozconf's output; refusing "
                f"to score a partial table.\n  {line!r}"
            )
        slug = match["slug"]
        outcomes.append(
            TestResult(
                slug=slug,
                column_id=column_id_for(slug),
                status=match["status"],  # type: ignore[arg-type]
                message=match["message"] or None,
            )
        )
    return outcomes


def verify_slugs(outcomes: list[TestResult], expected: set[str]) -> None:
    """Check the parsed results against the slugs ozconf said it would run.

    This is the guard that makes scraping safe. Every other failure mode -
    Rich wrapping a row, ozconf's runner aborting partway through, a duplicate
    line - shows up here as a set difference rather than as a quietly smaller
    denominator.

    Parameters
    ----------
    outcomes : list[Outcome]
        The parsed results.
    expected : set[str]
        The slugs reported by `ozconf find`.

    Raises
    ------
    ValueError
        If the parsed slugs don't exactly match `expected`, or repeat.
    """
    parsed = [outcome.slug for outcome in outcomes]
    duplicates = sorted({slug for slug, n in Counter(parsed).items() if n > 1})
    missing = sorted(expected - set(parsed))
    unexpected = sorted(set(parsed) - expected)

    if not (duplicates or missing or unexpected):
        return

    lines = [
        f"ozconf's results table does not match the {len(expected)} case(s) "
        f"`ozconf find` listed; refusing to score it."
    ]
    for label, slugs in (
        ("missing from the results", missing),
        ("not expected", unexpected),
        ("reported more than once", duplicates),
    ):
        if slugs:
            shown = ", ".join(slugs[:3])
            more = f" (and {len(slugs) - 3} more)" if len(slugs) > 3 else ""
            lines.append(f"  {len(slugs)} {label}: {shown}{more}")
    raise ValueError("\n".join(lines))


def summarize(outcomes: list[TestResult]) -> list[TestSummary]:
    """Aggregate outcomes into one summary per column.

    Parameters
    ----------
    outcomes : list[Outcome]
        Every case result from this run.

    Returns
    -------
    list[BucketSummary]
        One summary per column that had at least one case, sorted by column id.
    """
    counts: dict[str, Counter] = {}
    for outcome in outcomes:
        counts.setdefault(outcome.column_id, Counter())[outcome.status] += 1

    return [
        TestSummary(
            column_id=column_id,
            passed=tally["pass"],
            failed=tally["fail"],
            errored=tally["error"],
            skipped=tally["skip"],
        )
        for column_id, tally in sorted(counts.items())
    ]


def report(tool: Tool, summaries: list[TestSummary], outcomes: list[TestResult]) -> None:
    """Print a human-readable per-tool report.

    Parameters
    ----------
    tool : Tool
        The tool these results are for.
    summaries : list[TestSummary]
        The per-column aggregates.
    outcomes : list[TestResult]
        Every case result, used to describe the errors.
    """
    for summary in summaries:
        print(
            f"    {summary.column_id:<20} {summary.total:>4} cases  "
            f"{summary.passed:>4} pass  {summary.failed:>4} fail  "
            f"{summary.errored:>4} error  {summary.skipped:>4} skip  ->  "
            f"{summary.percentage:>5.1f}%"
        )

    unusable = [outcome for outcome in outcomes if outcome.status in ("error", "skip")]

    if unusable:
        warnings.warn(
            f"{tool.id}: {len(unusable)} of {len(outcomes)} case(s) did not produce a result."
        )


def load_existing(path: Path) -> dict:
    """Load a tool's existing YAML file, if it has one.

    Parameters
    ----------
    path : Path
        Path to conformance_results/local/<id>.yaml.

    Returns
    -------
    dict
        The parsed document, or an empty dict if `path` doesn't exist.
    """
    if not path.exists():
        return {}
    with open(path) as f:
        return yaml.safe_load(f) or {}


def build_document(
    existing: dict, tool: Tool, summaries: list[TestSummary]
) -> dict:
    """Create the new tool results document.

    This merges the new results with the old document.
    Versions that are tested in this run are replaced.
    Existing versions that are not tested this run are kept.

    Parameters
    ----------
    existing : dict
        The document currently on disk, from `load_existing`.
    tool : Tool
        The tool that was tested, as it described itself.
    summaries : list[BucketSummary]
        The per-column aggregates from this run.

    Returns
    -------
    dict
        The document to write, with keys in a stable order.
    """
    values = {summary.column_id: summary.percentage for summary in summaries}
    new_entry = {"version": tool.version, "values": values}

    old_versions = [
        entry for entry in existing.get("versions") or [] if isinstance(entry, dict)
    ]
    versions = [entry for entry in old_versions if entry.get("version") != tool.version]
    # Replace in place if this release is already listed, so re-running doesn't
    # reorder the table; otherwise append.
    position = next(
        (
            index
            for index, entry in enumerate(old_versions)
            if entry.get("version") == tool.version
        ),
        None,
    )
    if position is None:
        versions.append(new_entry)
    else:
        versions.insert(position, new_entry)

    document = {"id": tool.id, "name": tool.name}
    if tool.homepage:
        document["homepage"] = tool.homepage
    document["versions"] = versions
    return document


def write_document(document: dict, path: Path) -> None:
    """Validate and write a tool document.

    The document describes the summarized results for the website table.

    Parameters
    ----------
    document : dict
        The document from `build_document`.
    path : Path
        Where to write it.

    Raises
    ------
    pydantic.ValidationError
        If the document doesn't satisfy ConformanceResult.
    """
    ConformanceResult.model_validate(document)
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w") as f:
        f.write(DOCUMENT_HEADER)
        yaml.safe_dump(document, f, sort_keys=False, default_flow_style=False)
    print(f"Wrote {path}")


def test_tool_conformance(tool: Tool, expected: set[str], dry_run: bool) -> None:
    """Run the whole suite against one tool and record the result.

    Parameters
    ----------
    tool : Tool
        The tool to test.
    expected : set[str]
        The slugs `ozconf find` listed, used to verify the results table.
    dry_run : bool
        Print the document instead of writing it.

    Raises
    ------
    ValueError
        If any guard rejects this tool's run.
    """
    # The `--` is required so that the ozconf CLI doesn't claim the tool command
    # (i.e., uv run --script /path/to/my_dingus.py)
    test_command = [
        "ozconf", "test", KIND, "--include-profile", PROFILE, "--", *tool.command
    ]
    outcomes = parse_results(run_ozconf(test_command))
    verify_slugs(outcomes, expected)

    summaries = summarize(outcomes)
    report(tool, summaries, outcomes)

    document = build_document(load_existing(tool.output_file), tool, summaries)
    if dry_run:
        print(f"\n  --dry-run; would have written {tool.output_file}:")
        print(yaml.safe_dump(document, sort_keys=False, default_flow_style=False))
        return
    write_document(document, tool.output_file)


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(
        description=(
            "Run the ozconf conformance suite against every dingus in "
            "dinguses/, by scraping the `ozconf test` CLI, and write the "
            "results to conformance_results/local/<id>.yaml."
        )
    )
    parser.add_argument(
        "--list",
        action="store_true",
        help="List the registered dinguses.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Report the results without writing the YAML files.",
    )
    return parser.parse_args()


def main() -> int:
    """Test every registered dingus; see the module docstring."""
    args = parse_args()
    paths = discover()

    if args.list:
        for path in paths:
            print(f"{path.stem.removesuffix(DINGUS_SUFFIX):<20} {path}")
        return 0

    # Get info about all registered tools.
    tools: list[Tool] = []
    failures: list[tuple[str, str]] = []
    for path in paths:
        try:
            tools.append(describe(path))
        except ValueError as exc:
            print(f"ERROR [{path.name}]: {exc}")
            failures.append((path.name, str(exc)))

    if not tools:
        raise SystemExit("error: no dingus could describe itself; nothing to test.")

    # Get all of the tests ozconf expects to run.
    # This is used to validate the parsed output
    # (i.e., to make sure all expected tests have a result)
    find_command = ["ozconf", "find", KIND, "--include-profile", PROFILE]
    expected = {
        line.strip() for line in run_ozconf(find_command).splitlines() if line.strip()
    }
    if not expected:
        raise ValueError(
            f"ozconf reported no '{PROFILE}' cases for kind '{KIND}'."
        )

    for tool in tools:
        print(
            f"\n{tool.name} {tool.version}: running {len(expected)} '{PROFILE}' case(s)"
        )
        try:
            test_tool_conformance(tool, expected, args.dry_run)
        except ValueError as exc:
            print(f"ERROR [{tool.id}]: {exc}")
            failures.append((tool.id, str(exc)))

    if failures:
        print(
            f"\n{len(failures)} of {len(paths)} dingus(es) failed: "
            f"{', '.join(name for name, _ in failures)}",
        )
        return 1

    print("\nRun scripts/build_site.py to regenerate data/conformance_results.json.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
